vaadin/vaadin-core

tasks/cdn.js, tasks/config.js
connects to vaadin/components-team-tasks#6
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-components/17)
=> Fix cdn-destination after some changes in vaadin infra

CHANGES.md, README.md, bower.json, demo/index.html, ga.js, package.json, tasks/cdn.js, tasks/common.js, tasks/config.js, tasks/docsite.js, tasks/zip.js
connects to vaadin/components-team-tasks#19
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-components/19)
=> Rename components to Elements

apidoc/index.html
Connects to vaadin/components-team-tasks#34
=> Create links also for documented behaviors.

doc/elements-getting-started.md
Fixes vaadin/components-team-tasks#57
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-core-elements/30)
=> Add Getting Started chapter to documentation

doc/elements-introduction.md
Fixes vaadin/components-team-tasks#56
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-elements/29)
=> Add introduction chapter to documentation

README.md
Resolves vaadin/components-team-tasks#51
=> The vaadin-grid examples link now points to the http://vaadin.com/docs website

bower.json, tasks/config.js
Preparing for releasing vaadin-upload 1.0.0-alpha1
Closes vaadin/vaadin-upload#1
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-core-elements/35)
=> Adding vaadin-upload componet

docs/angular2.adoc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-core-elements/47)
=> Replace bs problem comment with a link

docs/angular2.adoc
Connected to vaadin/components-team-tasks#140
Connected to vaadin/components-team-tasks#134
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-core-elements/48)
=> Some improvements in doc related with ng2

gulpfile.js, tasks/config.js, tasks/zip.js
This PR adds a task to create the zip package for a vaadin-core-elements release. Not all previously deleted tasks are needed anymore (Sauli was right to delete those). 😄 
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-core-elements/51)
=> Restore ZIP related steps

tasks/docsite.js
Connects to vaadin/components-team-tasks#65
Do not merge this one until https://github.com/vaadin/vaadin-grid/pull/393 is merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-core-elements/59)
=> Remove separate task for vaadin-grid docs

index.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-core-elements/64)
=> Add vaadin-split-panel to the elements menu in index.html

README.md, bower.json, index.html, tasks/cdn.js
Fixes #69
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-core-elements/70)
=> Add context menu to master deploys

bower.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-core-elements/74)
=> Add "element-collection" keyword to bower.json

docs/elements-introduction.adoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-core-elements/77)
=> Make grid overview link use correct filename

bower.json
Fixes vaadin/vaadin-date-picker#281
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-core-elements/78)
=> Add Sugar to devDependencies

docs/elements-introduction.adoc, docs/integrations/integrations-vuejs.adoc
Fixes #76
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-core-elements/79)
=> Add vue.js docs

docs/elements-introduction.adoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-core-elements/81)
=> Fix integration links

README.md
This PR will allow us to use the `vaadin-core-elements` repo as a dashboard for overview the state of all components:
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-core-elements/88)
=> Add elements versions and build statuses

README.md
Replace unstable shields.io badges with fury.io:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-core-elements/90)
=> Replace shields.io bower badge with fury.io

bower.json, package.json
Connected to https://github.com/vaadin/components-team-tasks/issues/240
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-core-elements/100)
=> Relase 1.6.0

bower.json
Fixes https://github.com/vaadin/components-team-tasks/issues/241
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-core-elements/106)
=> Add paper-checkbox to devDependencies

docs/elements-getting-started.adoc, docs/elements-introduction.adoc
Fixes #110
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-core-elements/111)
=> Update introduction and getting started guide

bower.json, package.json
We need these changes in master because CI build to update https://cdn.vaadin.com/vaadin-core-elements/master is broken
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-core-elements/119)
=> Update vaadin dependencies to P2 versions

vaadin-core-elements.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-core-elements/122)
=> Fix wrong imports for new elements. Closes #121

bower.json
Include the master branch from vaadin-themes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-core-elements/123)
=> Add vaadin-themes

bower.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-core/162)
=> Remove unneeded complexity

.travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-core/163)
=> Add simple Travis build to detect dependency conflicts

bower.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-core/168)
=> Use grid beta5

DEVELOPMENT.md
Fixes #174
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-core/175)
=> Add development instructions for Polymer 3 convertion [skip ci]

CONTRIBUTING.md
Connected to https://github.com/vaadin/vaadin-element-skeleton/issues/146
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-core/190)
=> Add contribution.md

CONTRIBUTING.md
Actualise and restore some changes previously applied to the `p3-preview` branch in 93f7f52
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-core/205)
=> Update CONTRIBUTING.md with npm and ES modules info [skip ci]

vaadin-core.html, vaadin-core.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-core/210)
=> Add import for checkbox group

vaadin-core.html, vaadin-core.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-core/213)
=> Add import for checkbox group (#210)

.travis.yml
Same as vaadin/vaadin#48 (see description there).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-core/219)
=> Update node version to fix build on master

vaadin-core.html, vaadin-core.js
Fixes #229 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-core/228)
=> Add missing components imports for 14.1

vaadin-core.html, vaadin-core.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-core/230)
=> Add missing components imports for 14.2

vaadin-core.js
Fixes #229
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-core/232)
=> Add missing components imports

vaadin-core.html, vaadin-core.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-core/244)
=> Add imports for date-time-picker to 14.2

vaadin-core.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-core/245)
=> Add import for date-time-picker

vaadin-core.html, vaadin-core.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-core/252)
=> Add missing login-form imports to 14.2

vaadin-core.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-core/254)
=> Add missing login-form import to 17.0

vaadin-core.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-core/253)
=> Add missing login-form import to 16.0
